version: '3.8'

services:
  kafka-kraft:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: railway-kafka-kraft-local
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9999:9999"
    environment:
      KAFKA_CLUSTER_ID: "kraft-local-cluster-001"
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms256m"
      KAFKA_JVM_PERFORMANCE_OPTS: "-server -XX:+UseG1GC -XX:MaxGCPauseMillis=20"
      KAFKA_LOG_RETENTION_HOURS: "24"
      KAFKA_LOG_RETENTION_BYTES: "268435456"
      KAFKA_LOG_SEGMENT_BYTES: "268435456"
      KAFKA_NUM_PARTITIONS: "1"
      RAILWAY_PUBLIC_DOMAIN: "localhost"
      PORT: "9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  kafka_data:
    driver: local

networks:
  default:
    name: kafka-kraft-local